// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://copipddzqlmxstkucvmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvcGlwZGR6cWxteHN0a3Vjdm1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTg1MTgsImV4cCI6MjA3MDY3NDUxOH0.SFR49IyT5uFWvGjf9EoTNAeBWvA4HB4qvN_h9dQOuh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});